// Catálogo de tablas que el bot puede consultar en vivo vía la herramienta `consultar_tabla`.
// El valor es la lista de columnas conocidas (referencia para el modelo; "*" sigue funcionando).
export const TABLAS: Record<string, string> = {
  empleados: "id,cc,nombre,cargo,area,salario,tipo_contrato,fecha_inicio,fecha_fin,sede,estado,empresa_temporal_id",
  novedades: "id,empleado_id,concepto,tipo,cantidad,unidad,mes",
  incapacidades: "id,empleado_id,tipo,fecha_inicio,fecha_fin,dias,estado,obs",
  liquidaciones: "id,mes,total,num_empleados",
  empresas_temporales: "id,nombre",
  pedidos: "id,codigo,proveedor_nombre,categoria,fecha,estado,total,observaciones",
  detalle_pedidos: "id,pedido_id,nombre,cantidad,cantidad_recibida,unidad,precio_ref",
  remisiones: "id,pedido_id,proveedor,fecha,factura_numero,valor_remision,valor_factura,estado",
  items: "id,nombre,categoria,unidad,stock_actual,precio_ref,activo",
  bodegas: "id,nombre,activa",
  stock_bodega: "item_id,bodega_id,cantidad",
  proveedores: "id,nombre,nit,contacto,whatsapp,correo,estado",
  proveedor_categorias: "id,nombre",
  precios_historicos: "id,producto,proveedor,semana_label,precio,total,fecha_factura",
  activos: "id,codigo,nombre,marca,ubicacion,valor,estado,responsable,prox_mant",
  mantenimientos_activos: "id,activo_id,tipo,tecnico,fecha,costo,estado",
  solicitudes_mantenimiento: "id,activo,proveedor,tipo,descripcion,fecha,estado,costo_estimado",
  rotaciones: "id,empleado_id,sede_origen,sede_destino,fecha,motivo",
  turnos: "id,empleado_id,sede,horario_inicio,horario_fin,fecha,estado",
  sesiones_nutricionales: "id,fecha,tipo_servicio,total_venta,pacientes",
  remisiones_nutricionales: "id,sede,fecha,total_venta",
  precios_dieta: "id,dieta,desayuno,almuerzo,cena",
  empresa_areas: "id,nombre",
  empresa_cargos: "id,nombre",
  empresa_sedes: "id,nombre",
};
